### ISSUE TITLE
Queued notifications stop being sent after a few hours/days

### ISSUE THREAD

**Issue by chimit** [laravel-notification-channels/apn#104]
I'm using this package together with https://github.com/benwilkins/laravel-fcm-notification for Android push notifications. So I'm sending notifications into both channels at the same time:

```php
public function via($notifiable)
{
    return ['fcm', ApnChannel::class];
}
```

Everything works perfectly except for one strange problem. A few hours/days after restarting the queue driver (Redis) APN notifications stop being delivered (while Android via benwilkins' package keeps working without any problems). Nothing in logs, nothing in the `failed_jobs` table. It looks like everything is OK from the server perspective, but push notifications are not delivered.

I also tried a database queue driver before with the same result: autoincrement in the `jobs` table is "incrementing", but notifications are not delivered.

If I restart the queue driver everything starts working again until the next time. Missing notifications are not delivered after restarting. Only newly sent.

Do you have any ideas? Or maybe any suggestions on how to debug it?

**Comment by dwightwatson** [comment]
Make sure you're on the latest version - turns out that Apple tokens can expire, so we need to refresh them. v2.3.0 added a cache around the token to reuse a token for 20 minutes before refreshing it.

https://github.com/laravel-notification-channels/apn/releases/tag/v2.3.0

Let me know if that works for you, otherwise you can look at listening for the `Illuminate\Notifications\Events\NotificationFailed` event - it's fired internally when a notification fails to be delivered. It should contain information about what's going wrong (if it's running).
