### ISSUE TITLE
Unable to send badge zero with Laravel 6.

### ISSUE THREAD

**Issue by andrew-bibby** [laravel-notification-channels/apn#119]
I see there has been an update on PR #109 to resolve an issue where badges with a value fo zero were not being sent due to an int check. Currently I am on Laravel 6.0 (LTS) and noticed this issue and was happy to discover there has been a fix. Unfortunately the fix has been brought into the latest v3 and so as far as I can tell is uninstallable on Laravel 6.0 which I am fixed to.

Is the only way to solve this issue by upgrading to Laravel 8 and then updating this package? Is there any reason why the latest versions are not installable on Laravel 6.0 (LTS)?

**Comment by dwightwatson** [comment]
Looks like the last compatible version with Laravel 6.0 was v1.3.0 - from February 2020. Support would have been dropped in order to focus on the latest versions without having to worry about compatibility with older versions of Laravel an PHP. Continuing to support Laravel 6.0 properly would mean continuing to support PHP 7.2 which already end of life.

While Laravel 6.0 is LTS it doesn't imply that packages are required to maintain long term support as well.

I've had a stab at re-introducing support for Laravel 6.x and 7.x but only for PHP 7.3 and up (see #120) - would this work for your use-case? Going forward though, I'd likely remove support for these versions if they became difficult to maintain alongside later versions of Laravel.

**Comment by dwightwatson** [comment]
Tagged 3.3.0 which includes support for PHP 7.3+ and Laravel 6.x, 7.x and 8.x.

**Comment by andrew-bibby** [comment]
@dwightwatson 😄  thanks a lot for that. That gives me some time to schedule an upgrade. Appreciate that packages do not follow long term support along with Laravel. I will give this a try soon 👍
