### ISSUE TITLE
[Proposal] Change message based on device preferences

### ISSUE THREAD

**Issue by lucadegasperi** [laravel-notification-channels/apn#15]
Since a user can have multiple devices associated to them, some systems store preferences for each device instead of the user itself. It can happen that different devices of a same user use a different API version that needs a different notification payload.

This package already allows to send a notification to multiple devices for the same user at once. I think the next logical step would be to allow to send a different message for each device. What do you think?

**Comment by barryvdh** [comment]
So just the extra data, or the entire message? How would you see that?

**Comment by lucadegasperi** [comment]
My idea is that ```toApn($notifiable)``` should get called for each device token and not just for each user. Something similar to: ```toApn($notifiable, $device)```. ```$device``` could be more than just a token but an object that implements an interface to return a token, as well as containing other infos useful to personalize the message.

**Comment by dwightwatson** [comment]
Going to close the associated PR because it's fallen a little behind, but this is something I'd like to implement and take a little further. In addition to customisation per-device I think it would be worth adding the ability to change the connection credentials. For example, you might have users with different tokens and each token belongs to a unique iOS app - there's no way to do that at this point.

This problem has been mentioned over in laravel-notification-channels/gcm#25 so it would be good to see if we can find some generic solution that we could be consistent with.

**Comment by dwightwatson** [comment]
Unlikely to make any progress on this as it's very stale but happy to continue the discussion if it's still a feature that is wanted.
