### ISSUE TITLE
Add composer.lock to git

### ISSUE THREAD

**Issue by PauBenetPrat** [laravel-notification-channels/apn#40]
I think it would be a good idea to add composer.lock file to git as recommended [here](https://stackoverflow.com/a/12896850/5758080)

This way we'll be using exactly the same packages version!

Thanks!

**Comment by dwightwatson** [comment]
Having a `composer.lock` file makes perfect sense in the context of an application where each developer needs to be running the same code, and deployments need to get the code you've been testing against. 

However, it doesn't make as much sense in the context of packages. When you install this package into a Laravel application, Composer is going to work out what arrangement of dependencies will work for you and your app - it doesn't consider our `composer.lock` at all. 

Even in the context of the development of a package it's not totally important that we're all running the exact same versions of dependencies because our package is meant to support loose constraints (that is, Laravel 5.5 and up) rather than specific commits.

Hope this makes sense, I appreciate the suggestion but as above I don't think it's necessary for a package.
