### ISSUE TITLE
SPN - Can this package be used for websites?

### ISSUE THREAD

**Issue by deki23** [laravel-notification-channels/apn#74]
I'm implementing safari push notifications, the thing is I can get the device token from my Mac, but I'm not able to send notifications via this channel. I am using it for a web app, so I was wondering maybe this package cant be used for sending from websites to macOS, or I need the ios push certificate and the website push certificate? Currently, I am using one certificate(website push) to generate the push package and to send notifications to APN. 
[spn](https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/NotificationProgrammingGuideForWebsites/PushNotifications/PushNotifications.html#//apple_ref/doc/uid/TP40013225-CH3-SW1)

**Comment by dwightwatson** [comment]
I don't know enough about Safari Push Notifications but a quick browse of that documentation suggests it's the same platform underneath.

I'd suggest you test with this branch (https://github.com/laravel-notification-channels/apn/pull/67) rather than the current tagged version. It implements the newer standard (using .p8 certificates for authentication) and might get you in the right direction.

Please have a go and let me know.

**Comment by deki23** [comment]
Just solved it today, the problem was in payload data. I could not install the new package since its dependency is illuminate/support ^6.0, and I am using Laravel 5.5. But I will probably test it in the future, thanks for the help and this package. Cheers!
