### ISSUE TITLE
Send Notification to Log

### ISSUE THREAD

**Issue by lucadegasperi** [laravel-notification-channels/apn#9]
In some cases, when just testing the correct payload of the notification, I think it would be useful to have the notification logged instead of actually sent out.

What do you think? Do you have any suggestions on how I could test notifications without actually sending them?

**Comment by luisdalmolin** [comment]
I have done this in an SMS notification package by adding a `pretend` config option (https://github.com/luisdalmolin/laravel-zenvia-channel#configuration).

I think it's great to have such option.

**Comment by barryvdh** [comment]
I like this idea, would it make sense to do something like this across all packages?

**Comment by derekmd** [comment]
Without changing the framework's core, every laravel-notification-channels package would have to be updated to:

* dependency inject `Repository` _and_ `LoggerInterface` to channel classes.
* use an agreed configuration key to enable a global logging override of notification channels
* `send()` of each channel class is updated to write to the log instead of making the external Guzzle HTTP request, etc.

The drawbacks here are a messy mixing-of-concerns implementation and the fact Nexmo and Slack notifications built into the framework won't offer this ability. It also doesn't allow enabling log mode for only some notification channels. e.g., notifications sent to the database or email are fine but don't send external Twilio SMS messages.

## 5.4 pull request for `Illuminate\Notifications\NotificationSender`

Looking at classes in the `Illuminate\Notifications` namespace, this may be a requirement best afforded by the framework itself. [`ChannelManager`](https://github.com/laravel/framework/blob/master/src/Illuminate/Notifications/ChannelManager.php) can be updated similar to [`TransportManager`](https://github.com/laravel/framework/blob/master/src/Illuminate/Mail/TransportManager.php) by adding a `LogChannel` decorator class instantiated by a `ChannelManager@createLogDriver()` method.

[`NotificationSender@sendToNotifiable()`](https://github.com/laravel/framework/blob/master/src/Illuminate/Notifications/NotificationSender.php) would then be changed to use that global driver when configured. e.g.,

```php
protected function sendToNotifiable($notifiable, $id, $notification, $channel)
{
    if (! $notification->id) {
        $notification->id = $id;
    }

    if (! $this->shouldSendNotification($notifiable, $notification, $channel)) {
        return;
    }

    $driver = $this->manager->driver($channel);

    if ($this->app['config']['services.notifications.log']) { // ??
        $response = $this->manager->driver('log')->setDriver($driver)->send($notifiable, $notification);
    } else {
        $response = $driver->send($notifiable, $notification);
    } 

    $this->events->dispatch(
        new Events\NotificationSent($notifiable, $notification, $channel, $response)
    );
}
```

`LogChannel` can then check if a `log()` methods exists on the `$driver` channel object to get implementation-specific output. If it doesn't, there a choice to:

* attempt generic logging of the `$notification` object with `$notifiable` contact details
* throw an run-time exception
* instead call `$driver->send()`
* treat the condition as a noop pass-thru

Such an architecture change would allow pretend mode to be enabled globally for all notifications or configured logging to only some channels in the app.

**Comment by dwightwatson** [comment]
Is there any precedent within LNC for supporting logging now?

**Comment by dwightwatson** [comment]
Happy to implement this if some sort of standard could be agreed upon or if a PR is provided. Part of me is thinking that perhaps any `pretend` functionality for notifications might better belong in Laravel itself so it's handled at a global level, but I could be wrong there.
